name: Create Release
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: '*.git*'
    - name: Copy Archive To XPI
      uses: canastro/copy-file-action@master
      with:
        source: "release.zip"
        target: "release.xpi"
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "release.zip,release.xpi"
        token: ${{ secrets.TOKEN }}
